fix: strongly type get_configure_view
siemens/sentry-auth-oidc pull request #49
Opened 2024-08-20 13:26 UTC by reneluria

cf. https://github.com/getsentry/sentry/pull/75395

to be compatible with 24.8.0

2024-08-23 07:49 UTC, max-wittig commented
Looks good to me. I will try it out soon. We have not yet upgraded to 24.8.0, but will do so soon!

2024-09-03 13:39 UTC, max-wittig commented
Hi! Sorry for the late response. We got lots of stuff going on at the moment.

As you're updating this month. Do you mind taking a look, when you do? @dlouzan

2024-09-12 08:09 UTC, dlouzan commented
@reneluria Thanks for the contribution! I'm currently checking this on our stage system, we also need it for sentry 24.8.0 👍

2024-09-12 08:44 UTC, dlouzan requested changes
@reneluria Thanks, just did an initial pass, please take a look.

2024-09-12 08:44 UTC, dlouzan commented on oidc/provider.py
> +    name = ISSUER if ISSUER else "oidc"
@reneluria Could you elaborate on this change? We provide a way to customize the name via the `OIDC_ISSUER` config, as can be seen in the readme and constants.py.

/cc @max-wittig

2024-09-12 08:44 UTC, dlouzan commented on oidc/views.py
> +from sentry.plugins.base.response import DeferredResponse
I kwow we should have an auto-formatter here, could you re-order to keep the abc? 😄

2024-09-12 08:44 UTC, dlouzan commented on oidc/views.py
> +        "oidc/configure.html", {"provider_name": ISSUER or "", "domains": domains or []}
```suggestion
        "oidc/configure.html",
        {"provider_name": ISSUER or "", "domains": domains or []},
```

Just for consistency with the previous code.

2024-09-12 10:08 UTC, dlouzan commented
@reneluria We will also need a fix of the test setup to be able to run the test suite. Let me know if you're willing to take care of the required work, or we should take over.

2024-09-12 10:10 UTC, dlouzan commented on oidc/provider.py
> +    name = ISSUER if ISSUER else "oidc"
@reneluria I just had a chat with @max-wittig and we also tested the current behaviour without setting the `OIDC_ISSUER`, everything works. Please remove this guard and use the `OIDC_ISSUER` configuration with an appropriate value if you want to use `"oidc"` as your name. Thanks!

2024-09-12 12:31 UTC, max-wittig commented on oidc/views.py
> +from sentry.plugins.base.response import DeferredResponse
Let's fix that with an autoformatter later.

2024-09-12 13:48 UTC, reneluria commented on oidc/provider.py
> +    name = ISSUER if ISSUER else "oidc"
Ok, let's do this

2024-09-12 13:51 UTC, reneluria commented on oidc/views.py
> +        "oidc/configure.html", {"provider_name": ISSUER or "", "domains": domains or []}
ok

2024-09-12 14:34 UTC, dlouzan commented
@reneluria Thanks for addressing the open threads, we'll be merging this one now as our internal tests worked. There will be a new release once we fix the test setup, which we are doing in #51.

2024-09-12 14:35 UTC, dlouzan approved these changes

2024-09-12 14:39 UTC, reneluria commented
> @reneluria Thanks for addressing the open threads, we'll be merging this one now as our internal tests worked. There will be a new release once we fix the test setup, which we are doing in #51.

excellent, thank you

2024-09-12 14:46 UTC, merged